In [4]:
run crop_per_cell.py --help

usage: crop_per_cell.py [-h] [--margin MARGIN] image metadata outloc

produce per cell crops from image

positional arguments:
  image            path to image file
  metadata         path to metadata CSV
  outloc           output directory

optional arguments:
  -h, --help       show this help message and exit
  --margin MARGIN  margin factor (default: 0.2)

In [1]:
import pandas as pd
df = pd.read_parquet("/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/he_align/xenium_HE_aligned/cell_boundaries.parquet")
df.head()

      cell_id   vertex_x   vertex_y
0  aaaacgfd-1  49.614472  13.793826
1  aaaacgfd-1  49.609519  13.786525
2  aaaacgfd-1  49.608272  13.782869
3  aaaacgfd-1  49.605796  13.779221
4  aaaacgfd-1  49.598396  13.770702

In [3]:
import pandas as pd
df = pd.read_csv("/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/cell_boundaries.csv")
df.head()

      cell_id   vertex_x   vertex_y
0  aaaacgfd-1  2722.9750  796.02500
1  aaaacgfd-1  2721.7002  796.87500
2  aaaacgfd-1  2721.0625  797.08750
3  aaaacgfd-1  2720.4250  797.51250
4  aaaacgfd-1  2718.9375  798.78754

In [21]:
%%bash

slide='5087_5626A'
metadata_loc='5626A'
affine='/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/HE_alignment_files/matrix.csv'


image="/working/lab_quann/louiseN/BC_data/Xenium/40xHE/${slide}.ome.tif"
metadata="/working/lab_quann/louiseN/BC_data/Xenium/metadata/${metadata_loc}/cell_boundaries.csv"
output="/working/lab_quann/louiseN/benchmark/deeppt/segmented/${slide}_test"

python3 crop_per_cell.py $image $metadata $affine $output

Scale 1: x=1370–13445, y=31891–44224
Scale 2: x=2740–26891, y=63781–88449
Scale 4: x=5479–53782, y=127563–176898
Scale 8: x=10959–107563, y=255126–353796
Scale 16: x=21918–215127, y=510251–707591
Scale 32: x=43835–430253, y=1020503–1415183
Scale 64: x=87670–860507, y=2041006–2830365
    vertex_x   vertex_y       pixel_x      pixel_y
0  2722.9750  796.02500  40741.587990  2343.061023
1  2721.7002  796.87500  40743.237320  2344.147088
2  2721.0625  797.08750  40744.060796  2344.416238
3  2720.4250  797.51250  40744.885590  2344.959270
4  2718.9375  798.78754  40746.812212  2346.591570
5  2718.0876  799.63750  40747.913910  2347.680736
6  2717.6626  800.48755  40748.467977  2348.773170
7  2717.6626  801.12500  40748.472706  2349.594747
8  2717.4502  801.33750  40748.748034  2349.867052
9  2717.6626  801.76250  40748.477435  2350.416389
Image dims: 31933 x 33475
Pixel x range: 31890.7 – 44224.5
Pixel y range: 1369.9 – 13445.4
Skipped 354092 cells (boundary violations)

In [27]:
%%bash

image="/working/lab_quann/louiseN/BC_data/Xenium/metadata/1302A/HE.ome.tif"
metadata="/working/lab_quann/louiseN/BC_data/Xenium/metadata/1302A/cell_boundaries.csv"
affine='/working/lab_quann/louiseN/BC_data/Xenium/metadata/1302A/affine_matrix.json'
output="/working/lab_quann/louiseN/benchmark/deeppt/segmented/1302A_test"

python3 crop_per_cell.py $image $metadata $affine $output

Error while terminating subprocess (pid=833894):
   vertex_x  vertex_y      pixel_x       pixel_y
0  209.1000  841.7125  1275.948685  13153.369775
1  207.8250  841.9250  1276.233623  13155.011234
2  209.1000  844.9000  1280.053491  13153.346190
3  209.1000  845.9625  1281.421759  13153.338329
4  209.5250  846.8125  1282.512613  13152.784362
5  210.3750  847.4500  1283.326052  13151.684291
6  211.8625  847.0250  1282.765580  13149.770566
7  214.2000  847.4500  1283.292200  13146.755197
8  215.0500  846.1750  1281.642755  13145.669276
9  215.0500  845.3250  1280.548140  13145.675566
Image dims: 39077 x 39136
Pixel x range: 1175.0 – 14453.4
Pixel y range: -595.8 – 13299.2
Skipped 3170 cells (boundary violations)

Traceback (most recent call last):
  File "/mnt/backedup/home/louiseN/notebooks/deeppt/preprocessing/crop_per_cell.py", line 97, in <module>
    crop_per_cell(args.image, args.metadata, args.affine, args.margin, args.outloc)
  File "/mnt/backedup/home/louiseN/notebooks/deeppt/preprocessing/crop_per_cell.py", line 85, in crop_per_cell
    tifffile.imwrite(os.path.join(outloc, f'{im_name}_{id}.ome.tif'), cropped)
  File "/working/lab_quann/louiseN/miniconda3/envs/deeppt/lib/python3.9/site-packages/tifffile/tifffile.py", line 1439, in imwrite
    with TiffWriter(
  File "/working/lab_quann/louiseN/miniconda3/envs/deeppt/lib/python3.9/site-packages/tifffile/tifffile.py", line 1767, in __init__
    self._fh = FileHandle(file, mode=mode, size=0)
  File "/working/lab_quann/louiseN/miniconda3/envs/deeppt/lib/python3.9/site-packages/tifffile/tifffile.py", line 14659, in __init__
    self.open()
  File "/working/lab_quann/louiseN/miniconda3/envs/deeppt/lib/python3.9/site-packages/tifffile/tifffile.py", line 14678, in open
    self._fh = open(
KeyboardInterrupt

In [8]:
%%bash

image="/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/he_align/xenium_HE_aligned/morphology_focus.ome.tif"
metadata="/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/he_align/xenium_HE_aligned/cell_boundaries.parquet"
output="/working/lab_quann/louiseN/benchmark/deeppt/segmented/1302A_testv4"

python3 crop_per_cellv2.py $image $metadata $output

Image dims: 15967 x 16738
Pixel x range: 91.8 – 17182.0
Pixel y range: -483.0 – 16948.2
Skipped 20 cells (boundary violations)

In [12]:
import os
import tifffile

output_dir="/working/lab_quann/louiseN/benchmark/deeppt/segmented/1302A_testv4"
sizes = [tifffile.imread(os.path.join(output_dir, f)).shape for f in os.listdir(output_dir)[:50]]
print(sizes)

[(31, 30, 3), (28, 29, 3), (28, 36, 3), (26, 32, 3), (28, 34, 3), (22, 23, 3), (17, 19, 3), (32, 28, 3), (35, 41, 3), (11, 12, 3), (17, 18, 3), (30, 29, 3), (37, 39, 3), (36, 49, 3), (45, 40, 3), (26, 25, 3), (45, 31, 3), (70, 58, 3), (24, 24, 3), (44, 43, 3), (27, 31, 3), (20, 17, 3), (26, 34, 3), (16, 13, 3), (28, 30, 3), (32, 43, 3), (37, 33, 3), (33, 40, 3), (33, 42, 3), (26, 35, 3), (31, 41, 3), (21, 25, 3), (11, 10, 3), (18, 19, 3), (17, 18, 3), (38, 27, 3), (40, 32, 3), (31, 26, 3), (24, 27, 3), (24, 20, 3), (23, 25, 3), (26, 33, 3), (22, 26, 3), (47, 38, 3), (36, 37, 3), (38, 35, 3), (46, 42, 3), (18, 28, 3), (24, 21, 3), (63, 58, 3)]

In [7]:
import pandas as pd

cells = pd.read_parquet("/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/he_align/xenium_HE_aligned/cells.parquet")
print(cells.columns.tolist())
print(cells.head())

print(cells['x_centroid'].min(), cells['x_centroid'].max())
print(cells['y_centroid'].min(), cells['y_centroid'].max())

['cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area']
      cell_id  x_centroid  y_centroid  transcript_counts  \
0  aaaacgfd-1   49.592156   13.785015                 95
1  aaaafphi-1   48.114615   14.109472                 45
2  aaaagana-1   48.501275   13.688658                 60
3  aaaapbki-1   49.497400   14.108483                 29
4  aaabafca-1   49.537943   13.764650                 35

   control_probe_counts  control_codeword_counts  unassigned_codeword_counts  \
0                     0                        0                           0
1                     0                        0                           0
2                     0                        0                           0
3                     0                        0                           0
4                     0                        0                           0

   deprecated_codeword_counts  total_counts   cell_area  nucleus_area
0                           0            95   36.757189     22.307188
1                           0            45   26.867970     18.197969
2                           0            60   69.585784     41.001876
3                           0            29  163.555943           NaN
4                           0            35   35.763751     22.758751
0.3686276367875699 54.13176065314925
-1.4791822894340363 53.407035335677804

In [3]:
%%bash

cat /working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/HE_alignment_files/matrix.csv

0.00741812173164324,1.2888494261025938,1296.9052985636408
-1.2888494261025938,0.00741812173164324,44245.187745523275
0,0,1

In [15]:
import tifffile
with tifffile.TiffFile('/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/HE.ome.tif') as tif:
    for i, s in enumerate(tif.series):
        print(f"Series {i}: shape={s.shape}")

Series 0: shape=(31933, 33475, 3)

In [16]:
import tifffile
with tifffile.TiffFile('/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/HE.ome.tif') as tif:
    print(tif.pages[0].tags)

TiffTag 256 ImageWidth @24 LONG8 @36 = 33475
TiffTag 257 ImageLength @44 LONG8 @56 = 31933
TiffTag 258 BitsPerSample @64 SHORT[3] @76 = (8, 8, 8)
TiffTag 259 Compression @84 SHORT @96 = ADOBE_DEFLATE
TiffTag 262 PhotometricInterpretation @104 SHORT @116 = RGB
TiffTag 270 ImageDescription @124 ASCII[1562] @2555917690 = <?xml version="1.0"
TiffTag 277 SamplesPerPixel @144 SHORT @156 = 3
TiffTag 282 XResolution @164 RATIONAL @176 = (36526347, 1000)
TiffTag 283 YResolution @184 RATIONAL @196 = (36526398, 1000)
TiffTag 284 PlanarConfiguration @204 SHORT @216 = CONTIG
TiffTag 296 ResolutionUnit @224 SHORT @236 = CENTIMETER
TiffTag 305 Software @244 ASCII[23] @454 = OME Bio-Formats 6.12.0
TiffTag 322 TileWidth @264 LONG8 @276 = 1024
TiffTag 323 TileLength @284 LONG8 @296 = 1024
TiffTag 324 TileOffsets @304 LONG8[1056] @477 = (17373, 1638853, 2436630, 84820
TiffTag 325 TileByteCounts @324 LONG8[1056] @8925 = (830836, 797777, 829021, 79
TiffTag 330 SubIFDs @344 LONG8[6] @2555919252 = (1910402365, 2391273582, 251428
TiffTag 339 SampleFormat @364 SHORT @376 = UINT

In [17]:
import tifffile
with tifffile.TiffFile('/working/lab_quann/louiseN/BC_data/Xenium/metadata/5626A/HE.ome.tif') as tif:
    for i, level in enumerate(tif.series[0].levels):
        print(f"Level {i}: shape={level.shape}")

Level 0: shape=(31933, 33475, 3)
Level 1: shape=(15967, 16738, 3)
Level 2: shape=(7984, 8369, 3)
Level 3: shape=(3992, 4185, 3)
Level 4: shape=(1996, 2093, 3)
Level 5: shape=(998, 1047, 3)
Level 6: shape=(499, 524, 3)

In [ ]:
%%bash
set -ex

ome_folder='/working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A'
data_folder="/working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data" # compatible with deeppt pipeline naming conventions

for file in "$ome_folder"/*; do
    base=$(basename "$file" .ome.tif)
    vips tiffsave "$file" "${data_folder}/${base}.tif" --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
done

+ ome_folder=/working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A
+ data_folder=/working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaafeaa-1.ome.tif .ome.tif
+ base=5087_5165A_aaaafeaa-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaafeaa-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaafeaa-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaahipn-1.ome.tif .ome.tif
+ base=5087_5165A_aaaahipn-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaahipn-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaahipn-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaaiaok-1.ome.tif .ome.tif
+ base=5087_5165A_aaaaiaok-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaaiaok-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaaiaok-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaakieo-1.ome.tif .ome.tif
+ base=5087_5165A_aaaakieo-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaakieo-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaakieo-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaaljmp-1.ome.tif .ome.tif
+ base=5087_5165A_aaaaljmp-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaaljmp-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaaljmp-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaapeei-1.ome.tif .ome.tif
+ base=5087_5165A_aaaapeei-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaapeei-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaapeei-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabbnkj-1.ome.tif .ome.tif
+ base=5087_5165A_aaabbnkj-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabbnkj-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaabbnkj-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabdiio-1.ome.tif .ome.tif
+ base=5087_5165A_aaabdiio-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabdiio-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaabdiio-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabdkpa-1.ome.tif .ome.tif
+ base=5087_5165A_aaabdkpa-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabdkpa-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaabdkpa-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabfmej-1.ome.tif .ome.tif
+ base=5087_5165A_aaabfmej-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabfmej-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaabfmej-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabglje-1.ome.tif .ome.tif
+ base=5087_5165A_aaabglje-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabglje-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaabglje-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabpipk-1.ome.tif .ome.tif
+ base=5087_5165A_aaabpipk-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaabpipk-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaabpipk-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaacjnjo-1.ome.tif .ome.tif
+ base=5087_5165A_aaacjnjo-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaacjnjo-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaacjnjo-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaackjjb-1.ome.tif .ome.tif
+ base=5087_5165A_aaackjjb-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaackjjb-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaackjjb-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaacmmfd-1.ome.tif .ome.tif
+ base=5087_5165A_aaacmmfd-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaacmmfd-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaacmmfd-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadbgao-1.ome.tif .ome.tif
+ base=5087_5165A_aaadbgao-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadbgao-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadbgao-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadfenn-1.ome.tif .ome.tif
+ base=5087_5165A_aaadfenn-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadfenn-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadfenn-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadgeei-1.ome.tif .ome.tif
+ base=5087_5165A_aaadgeei-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadgeei-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadgeei-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadgill-1.ome.tif .ome.tif
+ base=5087_5165A_aaadgill-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadgill-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadgill-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadgpgn-1.ome.tif .ome.tif
+ base=5087_5165A_aaadgpgn-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadgpgn-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadgpgn-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadhonj-1.ome.tif .ome.tif
+ base=5087_5165A_aaadhonj-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadhonj-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadhonj-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadligl-1.ome.tif .ome.tif
+ base=5087_5165A_aaadligl-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadligl-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadligl-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadnlbn-1.ome.tif .ome.tif
+ base=5087_5165A_aaadnlbn-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadnlbn-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadnlbn-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadoeka-1.ome.tif .ome.tif
+ base=5087_5165A_aaadoeka-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadoeka-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadoeka-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadojkc-1.ome.tif .ome.tif
+ base=5087_5165A_aaadojkc-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaadojkc-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaadojkc-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeaefk-1.ome.tif .ome.tif
+ base=5087_5165A_aaaeaefk-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeaefk-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaeaefk-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeaoak-1.ome.tif .ome.tif
+ base=5087_5165A_aaaeaoak-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeaoak-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaeaoak-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaefbkk-1.ome.tif .ome.tif
+ base=5087_5165A_aaaefbkk-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaefbkk-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaefbkk-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeglfl-1.ome.tif .ome.tif
+ base=5087_5165A_aaaeglfl-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeglfl-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaeglfl-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaehjmp-1.ome.tif .ome.tif
+ base=5087_5165A_aaaehjmp-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaehjmp-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaehjmp-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaehmie-1.ome.tif .ome.tif
+ base=5087_5165A_aaaehmie-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaehmie-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaehmie-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeimak-1.ome.tif .ome.tif
+ base=5087_5165A_aaaeimak-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeimak-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaeimak-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaemjfg-1.ome.tif .ome.tif
+ base=5087_5165A_aaaemjfg-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaemjfg-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaemjfg-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeolkj-1.ome.tif .ome.tif
+ base=5087_5165A_aaaeolkj-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaaeolkj-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaaeolkj-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafaifb-1.ome.tif .ome.tif
+ base=5087_5165A_aaafaifb-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafaifb-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafaifb-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafbilh-1.ome.tif .ome.tif
+ base=5087_5165A_aaafbilh-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafbilh-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafbilh-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafccmk-1.ome.tif .ome.tif
+ base=5087_5165A_aaafccmk-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafccmk-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafccmk-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafjpdj-1.ome.tif .ome.tif
+ base=5087_5165A_aaafjpdj-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafjpdj-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafjpdj-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafkcah-1.ome.tif .ome.tif
+ base=5087_5165A_aaafkcah-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafkcah-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafkcah-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafmlda-1.ome.tif .ome.tif
+ base=5087_5165A_aaafmlda-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafmlda-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafmlda-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafoagi-1.ome.tif .ome.tif
+ base=5087_5165A_aaafoagi-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafoagi-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafoagi-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*
++ basename /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafojga-1.ome.tif .ome.tif
+ base=5087_5165A_aaafojga-1
+ vips tiffsave /working/lab_quann/louiseN/benchmark/deeppt/segmented/5087_5165A/5087_5165A_aaafojga-1.ome.tif /working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data/5087_5165A_aaafojga-1.tif --tile --pyramid --bigtiff --compression jpeg --Q 90 --tile-width 256 --tile-height 256 --strip
+ for file in "$ome_folder"/*

In [23]:
import tifffile
with tifffile.TiffFile('/working/lab_quann/louiseN/BC_data/Xenium/he/registered/1302A_0007311_he_registered.ome.tif') as tif:
    for i, level in enumerate(tif.series[0].levels):
        print(f"Level {i}: shape={level.shape}")

Level 0: shape=(3, 51556, 54190)
Level 1: shape=(3, 25778, 27095)
Level 2: shape=(3, 12889, 13547)
Level 3: shape=(3, 6444, 6773)
Level 4: shape=(3, 3222, 3386)
Level 5: shape=(3, 1611, 1693)
Level 6: shape=(3, 805, 846)
Level 7: shape=(3, 402, 423)

In [ ]:
%%bash
#build metadata file

data_folder="/working/lab_quann/louiseN/benchmark/deeppt/Xenium_slides_data"